# Generated by Django 6.1.1 on 2026-09-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medicines.reminder')),
            ],
        ),
    ]
